"""
Debug the AI mode: student critiques deliberately flawed AI explanations.
Grounded in Lane (2023) AI literacy and Bloom's Evaluate tier.
"""

import streamlit as st

from data.content import FLAWED_EXPLANATIONS
from services.feedback import get_debug_feedback
from services.knowledge import log_error, update_mastery


def render_debug() -> None:
    st.markdown("<h1>🐛 Debug the AI</h1>", unsafe_allow_html=True)
    st.markdown(
        '<p style="color:#94A3B8; margin-top:-0.5rem;">'
        "The AI made deliberate errors. Find them, explain why they're wrong, and correct them.</p>",
        unsafe_allow_html=True,
    )

    st.markdown("""
    <div class='card card-warn' style='margin-bottom:1.5rem;'>
        <div style='display:flex;gap:1rem;align-items:center;flex-wrap:wrap;'>
            <span class='badge badge-warn'>Lane (2023) — AI Literacy</span>
            <span class='badge badge-teal'>Bloom's: Evaluate & Critique</span>
            <span class='badge badge-blue'>AI4EDU — Critical Reasoning</span>
            <p style='margin:0.5rem 0 0; font-size:0.85rem; color:#94A3B8;'>
            Instead of asking the AI to solve problems for you, <em>you</em> are the expert who teaches the AI.
            This develops the most important skill for an AI-literate generation: knowing when to trust AI and when to challenge it.
            </p>
        </div>
    </div>
    """, unsafe_allow_html=True)

    col1, col2 = st.columns(2)
    with col1:
        debug_topic = st.selectbox("Select Topic:", list(FLAWED_EXPLANATIONS.keys()), key="debug_topic")
    with col2:
        available_concepts = list(FLAWED_EXPLANATIONS[debug_topic].keys())
        debug_concept = st.selectbox("Select Concept:", available_concepts, key="debug_concept")

    flawed_data = FLAWED_EXPLANATIONS[debug_topic][debug_concept]

    st.markdown("---")
    st.markdown("### 🤖 The AI's Explanation (Contains Errors!)")
    st.markdown("""
    <div class='card card-warn' style='margin-bottom:0.5rem;'>
        <p style='font-size:0.8rem; color:#FCD34D; margin:0 0 0.5rem;'>
        ⚠️ The following explanation was generated by an AI and contains deliberate conceptual errors.
        </p>
    </div>
    """, unsafe_allow_html=True)
    st.markdown(f'<div class="flawed-box">{flawed_data["flawed"]}</div>', unsafe_allow_html=True)

    st.markdown("---")
    st.markdown("### 🔍 Your Analysis")
    st.markdown(
        '<p style="font-size:0.9rem; color:#94A3B8;">What is WRONG with the AI\'s explanation? '
        "Be specific: what error did it make, and what is the correct approach?</p>",
        unsafe_allow_html=True,
    )

    student_critique = st.text_area(
        "Your critique:",
        height=120,
        placeholder="I found an error: the AI assumed... The correct approach is...",
        key="debug_critique",
    )

    if st.button("📤 Submit My Analysis", use_container_width=False, key="submit_debug"):
        if student_critique.strip():
            with st.spinner("🤖 Evaluating your critique..."):
                eval_feedback = get_debug_feedback(
                    flawed_data["flawed"], student_critique, debug_topic, debug_concept
                )
            st.session_state.debug_mode_feedback = eval_feedback
            log_error(debug_concept, "debug mode attempt — critique submitted")
            update_mastery(debug_concept, len(student_critique) > 50)
        else:
            st.warning("Please write your analysis before submitting.")

    if st.session_state.debug_mode_feedback:
        st.markdown(f"""
        <div class='card card-accent' style='margin-top:1rem;'>
            <div style='display:flex;align-items:center;gap:8px;margin-bottom:0.5rem;'>
                <span style='font-size:1.2rem;'>🎓</span>
                <strong style='color:#0D9488;'>Evaluation of Your Critique</strong>
            </div>
            <p style='margin:0; line-height:1.7;'>{st.session_state.debug_mode_feedback}</p>
        </div>
        """, unsafe_allow_html=True)

        st.markdown("### ✅ Official Error List")
        for i, err in enumerate(flawed_data["errors"], 1):
            st.markdown(f"""
            <div class='card card-err' style='margin-bottom:0.5rem;'>
                <p style='margin:0; font-size:0.9rem;'><strong style='color:#FCA5A5;'>Error {i}:</strong> {err}</p>
            </div>
            """, unsafe_allow_html=True)

        st.markdown(f"""
        <div class='card card-ok'>
            <p style='margin:0; font-size:0.9rem;'>
            <strong style='color:#86EFAC;'>✅ Correct explanation:</strong> {flawed_data["correct"]}
            </p>
        </div>
        """, unsafe_allow_html=True)
